name: predict_coffee
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"


dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  dio: ^5.1.1
  equatable: ^2.0.2
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_charts: ^0.5.1
  flutter_svg: ^2.0.4
  get_it: ^7.1.3
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  image_picker: ^0.8.6+2
  intl: ^0.17.0
  lottie: ^2.2.0
  ndialog: ^4.3.0
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/neurallink.json
  