name: predict_coffee
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  camera: ^0.10.5+2
  dartz: ^0.10.1
  dio: ^5.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_charts: ^0.5.1
  flutter_svg: ^2.0.6
  get_it: ^7.6.0
  go_router: ^7.1.1
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  ndialog: ^4.3.0
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  shared_preferences: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
